title: How to Get Rich (without getting lucky)
description: >- # this means to ignore newlines until "baseurl:"
  Learn how to get rich by seeking wealth, not money or status. 
  A tweetstorm by @naval.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://get-rich-sin-suerte.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: toysoldier182
github_username:  juancarlosasensio

# Config for multiple languages (i18n)
languages: ["en", "es"]
exclude_from_localizations: ["javascript", "images", "css"]

# Build settings
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
