title: How to Get Rich (without getting lucky)
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Seek wealth, not money or status.
  Wealth is having assets that earn while you sleep.
  A tweetstorm by @naval.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://get-rich-sin-suerte.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: toysoldier182
github_username:  juancarlosasensio

languages: ["en", "es"]

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
